### ISSUE TITLE
Update dependencies to make Floorist compatible with Python 3.10

### ISSUE THREAD

**Issue by Victoremepunto** [RedHatInsights/floorist#18]
The current package versions (specifically the *pyarrow version pinned to 5.0.0*) make Floorist incompatible with Python 3.10 (Again, PyArrow 5.0.0 package seems to require Python version <= 3.9). 

Maybe reviewing the available packages there's an update to make it work with the latest current stable Python release (3.10.2)

**Comment by skateman** [comment]
We can't move further without the missing ubi8 python3.10 base image.

**Comment by Victoremepunto** [comment]
We should stay tuned, https://github.com/sclorg/s2i-python-container/tree/master/3.10 - were can we ask for this image to be available ?
